services:
  - type: web
    name: discussionforum
    runtime: python
    plan: free
    branch: master
    buildCommand: cp config.example.py config.py && pip install -r requirements.txt && flask --app run:app db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PROFILE_UPLOADS_ENABLED
        value: "false"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
